### ISSUE TITLE
How do we use this in Meteor (right now)?

### ISSUE THREAD

**Issue by mizzao** [meteor/babel#3]
Matt's blog post (http://info.meteor.com/blog/whats-coming-in-meteor-12-and-beyond) seems to suggest that we can start using ES6 in Meteor projects, right now.

Is there a way to add this package into Meteor 1.1 apps and start using ES6 immediately? I'm guessing it's not as simple as `Npm.depends({"meteor-babel": ...})`, is it?

**Comment by stubailo** [comment]
The easiest way right now is to use the `jsx` package from the ongoing React project. But I suspect there will be some official integration coming very, very soon.

Here's the guide about JSX: http://react-in-meteor.readthedocs.org/en/latest/jsx/

**Comment by benjamn** [comment]
The trick is finding a way to compile all your app and/or package code using `meteor-babel`, and that's currently pretty straightforward if you put your ES6 code in files with an `.es6` file extension, and use a package like [`grigio:babel`](https://atmospherejs.com/grigio/babel).

As @stubailo points out, the `jsx` package is another good choice, especially if you're using React.

Meteor 1.2 will make ECMAScript 2015+ the default language for all `.js` files in Meteor apps, requiring no additional packages or configuration. Packages like `grigio:babel` can and should continue to exist, since they allow brave developers to experiment with features before they get turned on by default.

**Comment by mizzao** [comment]
Hey @benjamn and @stubailo , this all sounds great and I am very much looking forward to the integration.

I am currently trying to figure out how to write ES6-style packages with APIs while also generating JSDoc documentation. You guys must have some examples lying around somewhere; could you point me to a file or two?

**Comment by AdamBrodzinski** [comment]
@benjamn 

> Packages like grigio:babel can and should continue to exist, since they allow brave developers to experiment with features before they get turned on by default.

So there's not going to be a `.babelrc` file? React Native uses this and it works out really well.

**Comment by stubailo** [comment]
@AdamBrodzinski I think one thing to consider is that there are a lot more things to change than just turning Babel features on and off - there are different runtime options, polyfills, etc. I think we are basically going to turn on all of the features that make sense, so it might be hard to turn on something new just by changing an option.

**Comment by AdamBrodzinski** [comment]
@stubailo ah, that makes sense. Thanks!

**Comment by trusktr** [comment]
Hi @benjamn, I'm making [rocket:module](https://atmospherejs.com/rocket/module) (es6 syntax, modules, and cross-package npm dependencies). I haven't updated the README with docs yet because it's not released yet, but should be out soon. I've essentially made my own "batch handler", similar to what the `batch-plugins` branch will offer us when that's ready (through the use of `Plugin.registerCompiler`), so when `batch-plugins` is ready I'll refactor to use Plugin.registerCompiler. The basic idea is that the batch handler will compile all entry points (currently detected using `Plugin.registerSourceHandler` for files with the 'module.js' file extension). On the app-side of the build process, rocket:module's "batch handler" compiles all entry points, code splitting shared (npm) dependencies and modules out of all entry points into a file that gets loaded before all other files of packages that depend on `rocket:module` (it also handles app files too, not just package files). Entry points can be written in CJS, AMD, or ES6 module format (ES6 syntax included with any module format). Entry points, can `require`/`import` npm packages or local package files.

That's the gist. It's going to be finished soon (the first release, v1.0.0). I was wondering if you have any advice in this area. (: Does MDG have any plans to support ES6 Modules at some point? If so, what are the plans? I'd like to minimize duplicate work, and/or contribute to that since I'm already working on it. :smile:

**Comment by stubailo** [comment]
There's some content about it in this blog post: http://info.meteor.com/blog/whats-coming-in-meteor-12-and-beyond

The only information now is that modules will happen eventually, but not for 1.2.

**Comment by trusktr** [comment]
Thanks @stubailo (: I saw that blog post, which is actually why I was curious to ask about modules. Is there any plan at all (I mean like something concrete being written/drawn out somewhere)? How can I get more involved with that?

**Comment by benjamn** [comment]
This package has been part of Meteor since v1.2, in both the `babel-compiler` package and the implementation of the `meteor` command-line tool.

Shameless plug: Meteor 1.3.3 was [released](http://info.meteor.com/blog/announcing-meteor-1.3.3) today!
